---
title: "Auroral: Homoskedastic location families simulations"
author: "Nikos Ignatiadis"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteIndexEntry{Auroral: Homoskedastic location families simulations}
    \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preliminaries: Setup and load data

```{r warning=FALSE, message=FALSE, result=FALSE}
library(tidyverse)
library(cowplot)
library(ggrepel)
```

```{r}
files_dir <- file.path(getwd(),"..","simulation_scripts","files")
files_names <- file.path(files_dir, str_subset(list.files(files_dir), "homoskedastic"))
homosk_res <-  lapply(files_names, readRDS)
```

# Plotting 

```{r}
# http://tsitsul.in/blog/coloropt/
methods_list_homosk <- bind_rows( 
      tibble(method = "auroraKNN"        , method_pretty = "Aur-kNN"    , short ="A-KNN" , color="#00beff" ,  shrinkage="nonlinear"),
      tibble(method = "auroral"          , method_pretty = "Auroral"    , short = "Al"   ,  color="#4053d3",  shrinkage="linear"),
      tibble(method = "ccl"              , method_pretty = "CC-L / JS"       , short = "CC-L" ,  color="#ddb310",  shrinkage="linear"), 
      tibble(method = "gmleb"            , method_pretty = "NPMLE"      , short = "NPMLE",  color="#b51d14",  shrinkage="nonlinear"),
      tibble(method = "james_stein"      , method_pretty = "JS"         , short = "JS"   , color="#fb49b0" ,  shrinkage="linear"),
      tibble(method = "location_mean"    , method_pretty = "Mean"       , short = "Mean" , color="#8c9fb7" ,  shrinkage="no shrinkage"),
      tibble(method = "location_median"  , method_pretty = "Median"     , short = "Med." ,  color="#ff9287",  shrinkage="no shrinkage"),
      tibble(method = "location_midrange", method_pretty = "Midrange"   , short = "MR"   , color="#00bbad" ,  shrinkage="no shrinkage")
        ) %>%
      mutate(method_pretty=factor(method_pretty, levels=method_pretty))
```

A quick sanity check that CC-L and James-Stein agree. 


```{r}
js_ccl_diff_tbl <- bind_rows(homosk_res) %>% 
  group_by(method, A, Likelihood, Prior) %>%
  summarize(MSE=mean(error)) %>%
  filter(method %in% c("james_stein", "ccl")) %>%
  pivot_wider(names_from = method, values_from = MSE) %>%
  mutate(diff = ccl - james_stein)
max(abs(js_ccl_diff_tbl$diff))
```
```{r}
homoskedastic_eval_df <- bind_rows(homosk_res) %>% 
                         group_by(method, A, Likelihood, Prior) %>% 
                         summarize(MSE=mean(error)) %>%
                         filter(method != "gmleb_oracle") %>%
                         filter(method != "james_stein") %>%
                         left_join(methods_list_homosk) %>%
                         mutate(pretty_likelihood = paste0("'F = ",Likelihood,"'")) %>%
                         mutate(pretty_likelihood = factor(pretty_likelihood, levels=c("'F = Normal'", "'F = Laplace'", "'F = Rectangular'"))) %>%
                         mutate(pretty_prior = ifelse(Prior=="Normal","'Normal prior'", "'Three-point prior'"))

homosk_colors <- with(methods_list_homosk, setNames(color, method_pretty))
```

```{r fig.width=12, fig.height=8, fig.retina=10}
set.seed(1)
homosk_plot <- ggplot(homoskedastic_eval_df, aes(x = sqrt(A), y=MSE , col=method_pretty)) + 
                          geom_point(alpha=0.95, size=0.8) +
                          geom_text_repel(data=dplyr::filter(homoskedastic_eval_df,  A > 5.5 & A < 6.0), 
                                          aes(x = sqrt(A), y=MSE, col=method_pretty,
                                              label=method_pretty,
                                              segment.square  = TRUE,
                                              segment.inflect = TRUE),
                                          segment.colour="darkgrey",
                                          force = 1,
                                          nudge_x           = 0.25,
                                          direction         = "y", 
                                          segment.size      = 0.2,
                                          segment.curvature = -0.02,
                                          max.overlaps=Inf,
                                          min.segment.length = 0) + 
                          geom_line(size=0.7, alpha=0.9) +
                          scale_x_continuous(expand = expansion(mult = c(0.01,0.25))) + 
                          scale_y_log10(breaks=c(0.1,  0.4, 0.7, 1.0, 1.3, 1.6)) +
                          scale_color_manual(values=homosk_colors) + 
                          scale_fill_manual(values=homosk_colors) + 
                          xlab(expression('Prior standard deviation '*sqrt(A)))+
                          facet_grid(pretty_likelihood ~ pretty_prior, labeller = label_parsed)+ 
                          theme_cowplot() + 
                          theme(legend.title=element_blank(), legend.position = "none") 

homosk_plot
save_plot("homoskedastic_simulation.pdf", homosk_plot, base_height=10, base_width=14)
```   

 
```{r}
save_plot("homoskedastic_simulation.pdf", homosk_plot, base_height=8, base_width=12)
```


## Session info
```{r} 
library("sessioninfo")
options(width = 120)
session_info()
```